# Generated by Django 2.2.6 on 2021-04-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='desc',
            field=models.TextField(null=True, verbose_name='备忘录详情'),
        ),
    ]
